name: bw2class
channels:
  - conda-forge
  - cmutel
  - haasad
  - cardosan
  - romainsacchi/label/nightly
dependencies:
  - python =3.7
  - pip
  - brightway2
  - bw2calc >=1.8.0
  - bw2data >=3.6.2
  - bw2io >=0.7.12.1
  - bw2speedups
  - carculator
  - jupyter
  - klausen
  - matplotlib
  - numexpr
  - pandas
  - seaborn
  - xarray
  - xlrd
  - pip:
    - bw2temporalis
